# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@release
        with:
          dotnet-version: 3.1
      - name: Dotnet Publish
        run: dotnet publish . -c Release -o deploy
      
      - name: Stop old server and move it
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo service webserver stop; mv /webserver/current /webserver/old/build-`date +%y.%m.%d-%H:%M:%S`
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
      
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.5.3
        with:
          local: /home/runner/work/Warewolf-game/Warewolf-game/deploy/
          remote: ${{ secrets.REMOTE_TARGET }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
          
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo service webserver start
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
